FROM python:3.9-slim

WORKDIR /usr/src/app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY web-app/ .

EXPOSE 3001

ENV MONGO_URI=mongodb://mongodb:27017

ENV MONGO_DBNAME=expressions

CMD ["python", "app.py"]
