FROM python:3.9-slim

WORKDIR /usr/src/app

RUN apt-get update \
    && apt-get install -y libgl1-mesa-glx libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*


COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY machine-learning-client/ .


EXPOSE 3000

ENV MONGO_URI=mongodb://mongodb:27017

ENV MONGO_DBNAME=expressions

CMD ["python", "app.py"]
